Astra-AI:
  REPO_URL: "https://github.com/KhushiT-aptus/Astra-AI.git"
  DEPLOY_SERVER: "192.168.1.235"
aptusbot-demo:
  REPO_URL: "https://github.com/KhushiT-aptus/aptusbot-demo.git"
  DEPLOY_SERVER: "192.168.1.235"  
fastapi-test:
  REPO_URL: "https://github.com/KhushiT-aptus/fastapi-test.git"
  DEPLOY_SERVER: "192.168.1.235"  
pie-backend-chatbot:
  REPO_URL: "https://github.com/Amneal-pie/pie-backend-chatbot.git"
  DEPLOY_SERVER: "192.168.1.235" 
pie-backend-logs:
  REPO_URL: "https://github.com/Amneal-pie/pie-backend-logs.git"
  DEPLOY_SERVER: "192.168.1.235" 
pie-backend-dashboard:
  REPO_URL: "https://github.com/Amneal-pie/pie-backend-dashboard.git"
  DEPLOY_SERVER: "192.168.1.235"
Ra-Buddy:
  REPO_URL: "https://github.com/Amneal-pie/Ra-Buddy.git"
  DEPLOY_SERVER: "192.168.1.235"  
pie-backend-auth:
  REPO_URL: "https://github.com/Amneal-pie/pie-backend-auth.git"
  DEPLOY_SERVER: "192.168.1.235" 
pie-bl:
  REPO_URL: "https://github.com/Amneal-pie/pie-bl.git"
  DEPLOY_SERVER: "192.168.1.235" 
pie-ui:
  REPO_URL: "https://github.com/Amneal-pie/pie-ui.git"
  DEPLOY_SERVER: "192.168.1.235"  
fastapi-demo-app:
  REPO_URL: "https://github.com/SambitNandaAptus/fastapi-demo-app.git"
  DEPLOY_SERVER: "192.168.1.235" 
pie-RnD-bl:
  REPO_URL: "https://github.com/Amneal-pie/pie-RnD-bl "
  DEPLOY_SERVER: "192.168.1.235"   
  
  
